apiVersion: apps/v1
kind: Deployment
metadata:
  name: basic-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: faizanahmad055/backend:0.0.1
          ports:
            - containerPort: 8080
          env:
            - name: DB_NAME
              value: "testdb"
            - name: DB_USERNAME
              value: "sa"
            - name: DB_PASSWORD
              value: "password"
