apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc-0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: pv-test-0
  storageClassName: ""