apiVersion: v1
kind: ConfigMap
metadata:
  name: inventory-config
data:
  config.json: |
    {
      "apiBaseUrl": "http://backend.test.svc.cluster.local:8080/api/products",
      "version": "v2.0.0"
    }
