apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: your-docker-repo/frontend:latest
          ports:
            - containerPort: 80
          env:
            - name: API_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: inventory-config
                  key: API_BASE_URL
